Steps tmp commented

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,170 +37,170 @@ jobs:
           TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
           YC_TOKEN: ${{ secrets.YC_TOKEN }}
 
-#  pep8:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Check out repository code
-#        uses: actions/checkout@v3
-#
-#      - name: Set up Python
-#        uses: actions/setup-python@v4
-#        with:
-#          python-version: 3.9
-#
-#      - name: Install dependencies
-#        run: |
-#          python -m pip install --upgrade pip
-#          pip install flake8==6.0.0 flake8-isort==6.0.0
-#
-#      - name: Test with flake8
-#        run: python -m flake8 backend/
-#
-#  build-and-push-backend-image:
-#    runs-on: ubuntu-latest
-#    needs: pep8
-#    steps:
-#      - name: Check out repository code
-#        uses: actions/checkout@v3
-#
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v2
-#
-#      - name: Login to Docker
-#        uses: docker/login-action@v2
-#        with:
-#          username: ${{ secrets.DOCKERHUB_USERNAME }}
-#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
-#
-#      - name: Push to DockerHub
-#        uses: docker/build-push-action@v4
-#        with:
-#          context: ./backend/
-#          push: true
-#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest
-#
-#  build-and-push-frontend-image:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Check out repository code
-#        uses: actions/checkout@v3
-#
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v2
-#
-#      - name: Login to Docker
-#        uses: docker/login-action@v2
-#        with:
-#          username: ${{ secrets.DOCKERHUB_USERNAME }}
-#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
-#
-#      - name: Push to DockerHub
-#        uses: docker/build-push-action@v4
-#        with:
-#          context: ./frontend/
-#          push: true
-#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest
-#
-#  build-and-push-gateway-image:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Check out repository code
-#        uses: actions/checkout@v3
-#
-#      - name: Set up Docker Buildx
-#        uses: docker/setup-buildx-action@v2
-#
-#      - name: Login to Docker
-#        uses: docker/login-action@v2
-#        with:
-#          username: ${{ secrets.DOCKERHUB_USERNAME }}
-#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
-#
-#      - name: Push to DockerHub
-#        uses: docker/build-push-action@v4
-#        with:
-#          context: ./nginx/
-#          push: true
-#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest
-#
-#  deploy:
-#    runs-on: ubuntu-latest
-#    needs:
-#      - build-and-push-backend-image
-#      - build-and-push-frontend-image
-#      - build-and-push-gateway-image
-#      - create-server
-#    steps:
-#      - name: Checkout repo
-#        uses: actions/checkout@v3
-#
-#      - name: Copy docker-compose.yml via ssh
-#        uses: appleboy/scp-action@master
-#        with:
-#          host: ${{ needs.create-server.outputs.server_ip }}
-#          username: ${{ secrets.SERVER_USER }}
-#          key: ${{ secrets.SERVER_SSH_KEY }}
-#          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
-#          source: "docker-compose.production.yml"
-#          target: "kittygram"
-#
-#      - name: Create .env file
-#        run: |
-#          touch .env
-#          echo "POSTGRES_HOST=postgres" > .env
-#          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
-#          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
-#          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
-#          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
-#
-#      - name: Copy .env via ssh
-#        uses: appleboy/scp-action@master
-#        with:
-#          host: ${{ needs.create-server.outputs.server_ip }}
-#          username: ${{ secrets.SERVER_USER }}
-#          key: ${{ secrets.SERVER_SSH_KEY }}
-#          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
-#          source: ".env"
-#          target: "kittygram"
-#
-#      - name: Wait for Docker to be ready (with retries)
-#        uses: appleboy/ssh-action@master
-#        with:
-#          host: ${{ needs.create-server.outputs.server_ip }}
-#          username: ${{ secrets.SERVER_USER }}
-#          key: ${{ secrets.SERVER_SSH_KEY }}
-#          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
-#          script: |
-#            echo "Waiting for Docker to start..."
-#            timeout=60  # Максимум 60 секунд ожидания
-#            while [ $timeout -gt 0 ]; do
-#              if sudo docker info &>/dev/null; then
-#                echo "Docker is ready!"
-#                exit 0
-#              fi
-#              echo "Docker not ready yet, retrying in 5s... (${timeout}s left)"
-#              sleep 5
-#              timeout=$((timeout - 5))
-#            done
-#            echo "ERROR: Docker did not start in time!"
-#            exit 1
-#
-#      - name: Executing remote ssh commands to deploy
-#        uses: appleboy/ssh-action@master
-#        with:
-#          host: ${{ needs.create-server.outputs.server_ip }}
-#          username: ${{ secrets.SERVER_USER }}
-#          key: ${{ secrets.SERVER_SSH_KEY }}
-#          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
-#          script: |
-#            cd kittygram
-#            sudo docker compose -f docker-compose.production.yml pull
-#            sudo docker compose -f docker-compose.production.yml down
-#            sudo docker compose -f docker-compose.production.yml up -d
+  pep8:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install flake8==6.0.0 flake8-isort==6.0.0
+
+      - name: Test with flake8
+        run: python -m flake8 backend/
+  #
+  #  build-and-push-backend-image:
+  #    runs-on: ubuntu-latest
+  #    needs: pep8
+  #    steps:
+  #      - name: Check out repository code
+  #        uses: actions/checkout@v3
+  #
+  #      - name: Set up Docker Buildx
+  #        uses: docker/setup-buildx-action@v2
+  #
+  #      - name: Login to Docker
+  #        uses: docker/login-action@v2
+  #        with:
+  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+  #
+  #      - name: Push to DockerHub
+  #        uses: docker/build-push-action@v4
+  #        with:
+  #          context: ./backend/
+  #          push: true
+  #          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest
+  #
+  build-and-push-frontend-image:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to Docker
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
+      - name: Push to DockerHub
+        uses: docker/build-push-action@v4
+        with:
+          context: ./frontend/
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest
+  #
+  #  build-and-push-gateway-image:
+  #    runs-on: ubuntu-latest
+  #    steps:
+  #      - name: Check out repository code
+  #        uses: actions/checkout@v3
+  #
+  #      - name: Set up Docker Buildx
+  #        uses: docker/setup-buildx-action@v2
+  #
+  #      - name: Login to Docker
+  #        uses: docker/login-action@v2
+  #        with:
+  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+  #
+  #      - name: Push to DockerHub
+  #        uses: docker/build-push-action@v4
+  #        with:
+  #          context: ./nginx/
+  #          push: true
+  #          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest
+  #
+  #  deploy:
+  #    runs-on: ubuntu-latest
+  #    needs:
+  #      - build-and-push-backend-image
+  #      - build-and-push-frontend-image
+  #      - build-and-push-gateway-image
+  #      - create-server
+  #    steps:
+  #      - name: Checkout repo
+  #        uses: actions/checkout@v3
+  #
+  #      - name: Copy docker-compose.yml via ssh
+  #        uses: appleboy/scp-action@master
+  #        with:
+  #          host: ${{ needs.create-server.outputs.server_ip }}
+  #          username: ${{ secrets.SERVER_USER }}
+  #          key: ${{ secrets.SERVER_SSH_KEY }}
+  #          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
+  #          source: "docker-compose.production.yml"
+  #          target: "kittygram"
+  #
+  #      - name: Create .env file
+  #        run: |
+  #          touch .env
+  #          echo "POSTGRES_HOST=postgres" > .env
+  #          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
+  #          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
+  #          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
+  #          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
+  #
+  #      - name: Copy .env via ssh
+  #        uses: appleboy/scp-action@master
+  #        with:
+  #          host: ${{ needs.create-server.outputs.server_ip }}
+  #          username: ${{ secrets.SERVER_USER }}
+  #          key: ${{ secrets.SERVER_SSH_KEY }}
+  #          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
+  #          source: ".env"
+  #          target: "kittygram"
+  #
+  #      - name: Wait for Docker to be ready (with retries)
+  #        uses: appleboy/ssh-action@master
+  #        with:
+  #          host: ${{ needs.create-server.outputs.server_ip }}
+  #          username: ${{ secrets.SERVER_USER }}
+  #          key: ${{ secrets.SERVER_SSH_KEY }}
+  #          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
+  #          script: |
+  #            echo "Waiting for Docker to start..."
+  #            timeout=60  # Максимум 60 секунд ожидания
+  #            while [ $timeout -gt 0 ]; do
+  #              if sudo docker info &>/dev/null; then
+  #                echo "Docker is ready!"
+  #                exit 0
+  #              fi
+  #              echo "Docker not ready yet, retrying in 5s... (${timeout}s left)"
+  #              sleep 5
+  #              timeout=$((timeout - 5))
+  #            done
+  #            echo "ERROR: Docker did not start in time!"
+  #            exit 1
+  #
+  #      - name: Executing remote ssh commands to deploy
+  #        uses: appleboy/ssh-action@master
+  #        with:
+  #          host: ${{ needs.create-server.outputs.server_ip }}
+  #          username: ${{ secrets.SERVER_USER }}
+  #          key: ${{ secrets.SERVER_SSH_KEY }}
+  #          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
+  #          script: |
+  #            cd kittygram
+  #            sudo docker compose -f docker-compose.production.yml pull
+  #            sudo docker compose -f docker-compose.production.yml down
+  #            sudo docker compose -f docker-compose.production.yml up -d
 
   autotests:
     runs-on: ubuntu-latest
-#    needs: deploy
+    #    needs: deploy
     needs: create-server
     steps:
       - name: Checkout repo
